### ISSUE TITLE
13 Test fails with message: 75Error retrieving information from server. DF-DFERH-01

### ISSUE THREAD

**Issue by its-mash** [GoneToneStudio/node-google-play-api#1]
All the failed tests giving the same error: "75Error retrieving information from server. DF-DFERH-01" though authentication test passed. See attached image:

![gp1](https://user-images.githubusercontent.com/13703633/128965621-72513f7b-3a86-401c-a332-7a1b7eed8ee2.png)

**Comment by GoneTone** [comment]
My test is successful.

How did you test?

![image](https://user-images.githubusercontent.com/10025956/128975234-51ccd7c8-2b69-4277-854d-bb997fdb540f.png)

**Comment by its-mash** [comment]
Hi, I have done the following to test:
- `npm install `
- created a .env file in the root directory with bellow content
    GOOGLE_TEST_EMAIL=myemail
    GOOGLE_TEST_GFS_ID=GFS ID from the suggested app
    GOOGLE_TEST_AUTH_TOKEN=Token retrieved following your instruction
- `npm run test`

I believe, no wrong with following your instructions. Maybe the cause is something related to other layers of security of Google other than "Enabling access to less secure(already enabled)". Different accounts may behave differently here. I will try with a different google account.

**Comment by GoneTone** [comment]
Your `GOOGLE_TEST_AUTH_TOKEN` string start with `aas_et/` or `oauth2_4/` ?
Which one is it?

**Comment by its-mash** [comment]
starts with oauth2_4/

**Comment by GoneTone** [comment]
The correct string start is `aas_et/`.

You must use `gpAPI.getGoogleToken()` to get!

Example:
```javascript
gpAPI.getGoogleToken('Your OAuth2 Token', 'save/token.txt').then(async (token) => {
  await gpAPI.googleAuth(token)

  const details = await gpAPI.appDetails('com.github.android')

  console.log(`Title: ${details.title}`)
  console.log(`Description Html: ${details.descriptionHtml}`)
  console.log(`Developer Name: ${details.details.appDetails.developerName}`)
  console.log(`Version Code: ${details.details.appDetails.versionCode}`)
  console.log(`Version String: ${details.details.appDetails.versionString}`)
  console.log(`Package Name: ${details.details.appDetails.packageName}`)
  console.log(`Share Url: ${details.shareUrl}`)
  
  console.log(details)
})
```

**Comment by its-mash** [comment]
It worked! Thanks. btw what's your progress on "A version of this library for PHP is being developed." I need to port it to PHP, we can work together...

**Comment by GoneTone** [comment]
Recently I have many projects under development, PHP version is temporarily suspended.
