### ISSUE TITLE
Wrong exception when trying to download unsupported apk

### ISSUE THREAD

**Issue by dudul** [GoneToneStudio/node-google-play-api#10]
Hi,
When trying to download an apk and it's not supported by the device, the "`this.purchase`" throw this exception:
`Purchase Request Failed: Cannot read property 'toString' of null`

This happened because `this.appDetails(packageName)` doesn't fetch the `appDetails.details.appDetails.versionCode` (I guess it's not available when the device is not supported by the apk) and then pass undefined `versionCode`.

When (just for testing) I added this line before the actual purchase, 
```
if(!versionCode){
        versionCode = 0;
}
```
it return the correct error (I guess)
`Error retrieving information from server. DF-DFERH-01`

It can be tested with this apk `com.macmillan.navio` (I think it support only big screens)

**Comment by GoneTone** [comment]
Fixed!
