### ISSUE TITLE
Old APK

### ISSUE THREAD

**Issue by 89z** [GoneToneStudio/node-google-play-api#11]
Is it possible to get old APK from this package, or just latest version? Similar to this:

https://www.apkmirror.com/uploads/?q=github-2

**Comment by GoneTone** [comment]
Version v1.2.0 has been released, can specify the app version code to download.

Example:

```javascript
gpAPI.getGoogleToken('Your OAuth2 Token', 'save/token.txt').then(async (token) => {
  await gpAPI.googleAuth(token)

  await gpAPI.downloadApk('com.github.android', 'save_folder', 613) // Specify Version Code
})
```

**Comment by 89z** [comment]
How to enumerate available versions?
