### ISSUE TITLE
Get Split Delivery Data Info return null

### ISSUE THREAD

**Issue by Thanhan0901** [GoneToneStudio/node-google-play-api#13]

**Comment by Thanhan0901** [comment]
I manipulate the application com.riotgames.league.wildriftvn using the function Get Split Delivery Data Info but returned an empty array

**Comment by GoneTone** [comment]
Sorry, I don’t have a supported device to test.

Usually if it returned an empty array instead of returnedan error, it should be normal.

**Comment by Thanhan0901** [comment]
so how can get a complete xapk file like apkpure

**Comment by GoneTone** [comment]
Is it convenient to give me your GSF ID for testing?

You can send to this email: p29022716@gmail.com

**Comment by 89z** [comment]
I can get it with my program:

~~~
PS C:\> googleplay -a com.riotgames.league.wildriftvn
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.riotgames.league.wildriftvn
&{NumDownloads:4.874 M Offer:0.00 USD Size:93.281 MB Title:LMHT: Tốc Chiến
VersionCode:517831 VersionString:2.6.0.5178}
~~~
