### ISSUE TITLE
Error when download apk of some app

### ISSUE THREAD

**Issue by smallfirelkp** [GoneToneStudio/node-google-play-api#15]
I try to download apk with downloadApk func , some app like `com.roblox.client`, `com.miHoYo.GenshinImpact`
downloaded successfuly, but some app like: `com.supercell.clashmini` got error with this messages: `Download Info Failed: Make "com.supercell.clashmini" Purchase Request Failed: Error retrieving information from server. DF-DFERH-01` . 
Anyone have solution for this issue?

**Comment by GoneTone** [comment]
Does your device support the app `com.supercell.clashmini`?
Unable to download if it not support.

**Comment by smallfirelkp** [comment]
> Does your device support the app `com.supercell.clashmini`? Unable to download if it not support.

Yeah, first i try to change UserAgent but same error, but when i changed the GSFID too, it's worked.
Thank you!
