### ISSUE TITLE
versionString: null

### ISSUE THREAD

**Issue by 89z** [GoneToneStudio/node-google-play-api#5]
Using this program:

~~~js
const GooglePlayAPI = require('@gonetone/google-play-api');

var gpAPI = new GooglePlayAPI("Your_Google_Account@gmail.com", "The GSF ID (Google Service Framework ID) of your device");

gpAPI.getGoogleToken(
   'Your OAuth2 Token',
   'token.txt'
).then(async (token) => {
   await gpAPI.googleAuth(token);
   const details = await gpAPI.appDetails('com.github.android');
   console.log(details.details.appDetails);
})

~~~

I get expected version:

~~~
versionCode: 607,
versionString: '1.27.0',
~~~

but with different package:

~~~js
const details = await gpAPI.appDetails('com.google.android.youtube');
~~~

no version:

~~~
versionCode: null,
versionString: null,
~~~

**Comment by GoneTone** [comment]
My test is work...

Test code:

```javascript
const GooglePlayAPI = require('@gonetone/google-play-api')

const gpAPI = new GooglePlayAPI("Your_Google_Account@gmail.com", "The GSF ID (Google Service Framework ID) of your device")

gpAPI.getGoogleToken('Your OAuth2 Token', 'save/token.txt').then(async (token) => {
  await gpAPI.googleAuth(token)

  const details = await gpAPI.appDetails('com.google.android.youtube')

  console.log(`Version Code: ${details.details.appDetails.versionCode}`)
  console.log(`Version String: ${details.details.appDetails.versionString}`)
})
```

Result:

![image](https://user-images.githubusercontent.com/10025956/131224896-60bc959c-debc-40be-afd7-a13461694bf5.png)

**Comment by GoneTone** [comment]
Also, please don’t disclose any of your account information...

**Comment by 89z** [comment]
on this page

https://accounts.google.com/EmbeddedSetup

when I click I AGREE - the token is generated, but the screen gets stuck, it keeps loading forever

**Comment by GoneTone** [comment]
loading forever is normal.
You can close the page after get the token.

**Comment by 89z** [comment]
I got it to work! I am using Android Virtual Device, but I think the problem was using older API. I switched to API 30 and seems to be working now. Thanks!

**Comment by 89z** [comment]
Yeah, the API was the issue. Using API 24 fails, but API 25 or higher works. You might want to mention that in the documentation, as it applied to all devices, not just Virtual Devices.

**Comment by GoneTone** [comment]
The API version supported by each APP is different.
Default API version of this library is 28.

**Comment by 89z** [comment]
No, I mean Android API

**Comment by GoneTone** [comment]
oh, understand
