### ISSUE TITLE
Password login

### ISSUE THREAD

**Issue by 89z** [GoneToneStudio/node-google-play-api#6]
is it possible to login with email and password instead of long token? This tool can do it:

https://github.com/matlink/gplaycli

**Comment by GoneTone** [comment]
All the password login methods I know are no longer valid, I’m not sure if it is feasible.

That tool is work?

**Comment by 89z** [comment]
this one works, I tested it:

https://github.com/simon-weber/gpsoauth

**Comment by GoneTone** [comment]
I will study it when I have time

**Comment by 89z** [comment]
Here is a sample request:

~~~
POST /auth HTTP/1.1
Host: android.clients.google.com
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 240
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ODl6OmE1NzYxMjZlNzVlZjZiY2Y5ZDljNzEyZWIyN2RmZjFmOGFhZmQ1MWU=

Email=srpen6%40gmail.com&
EncryptedPasswd=AFcb4KQ5eLLIo6bMHm4mQwEFTVRWsdCpsvQYvq-S6wnwbbndZs0GTKdjnDLDb...&
sdk_version=17
~~~

**Comment by GoneTone** [comment]
EncryptedPasswd I still need to study

**Comment by 89z** [comment]
check here:

https://github.com/simon-weber/gpsoauth/blob/36f1d393/gpsoauth/google.py#L50-L62

**Comment by GoneTone** [comment]
I will try it when I have time, thanks!

**Comment by 89z** [comment]
Closing this in favor of my own package:

~~~
googleplay -e EMAIL -p PASSWORD
~~~

https://github.com/89z/googleplay
