### ISSUE TITLE
Get package's supported devices

### ISSUE THREAD

**Issue by dudul** [GoneToneStudio/node-google-play-api#9]
Hi,
Is there a way to determinate the supported device types for a package?
For example `com.google.android.youtube.tv` is compatible only for Android TV.
The Play store shows you the compatible and not compatible (with a reason) devices .

![play](https://user-images.githubusercontent.com/4558838/133221801-c920c51e-e718-4f28-bd22-140b4047e9bd.png)

The `downloadApk()` return this error 
`Make "com.android.chrome" Purchase Request Failed: Error retrieving information from server. DF-DFERH-01`

**Comment by GoneTone** [comment]
You must confirm by yourself whether the app supports your device.

**Comment by GoneTone** [comment]
This library cannot get list of supported devices.
